### ISSUE TITLE
Pixelmon and HBM use a lot of RAM.

### ISSUE THREAD

**Issue by Levakiv** [ThePansmith/FTMpack#5]
**Describe**
Modpack is impossible to run on 10 gigabytes of RAM. This problem is caused by the following mods: Pixelmon and Hbm's Nuclear Tech Mod Reloaded.
**Solution:**
Add <a href="https://www.curseforge.com/minecraft/mc-mods/texfix"> TexFix </a> mod (reduced RAM consumption).
Pixelmon and Pokecube can be reduced RAM consumption with a resource pack that only replaces textures (without changing models).
<details>
  <summary>Pixelmon and Pokecube AIO</summary>
Without resourcepack <code>tNumber of pixels by width = the number of textures with a given number of pixels in width
</code><br>
<code>512=3161, 1024=180, 2048=8, 514=2, 518=2, 520=1, 1554=1, 530=2, 533=4, 534=1, 1046=2, 32=3371, 33=10, 34=25, 35=12, 36=24, 37=23, 38=13, 39=13, 40=16, 553=1, 41=23, 42=38, 43=28, 44=34, 1069=4, 45=50, 46=25, 559=7, 47=30, 48=92, 560=3, 49=24, 50=48, 51=36, 52=19, 53=32, 54=32, 55=23, 56=29, 57=37, 58=27, 570=1, 59=27, 60=19, 61=23, 62=42, 63=40, 64=944, 1088=5, 65=27, 66=42, 67=22, 68=29, 69=32, 70=31, 71=31, 72=45, 73=34, 74=30, 75=48, 76=35, 77=31, 78=35, 79=30, 80=83, 81=14, 82=39, 83=15, 84=296, 85=51, 86=24, 87=26, 88=12, 600=20, 89=27, 90=22, 91=27, 92=33, 93=13, 94=22, 95=29, 96=17, 608=2, 97=11, 98=14, 99=136, 100=135, 101=4, 102=2, 103=15, 104=371, 105=5, 106=5, 107=3, 108=32, 109=11, 110=16, 111=13, 112=7, 113=13, 114=4, 115=15, 116=11, 117=8, 118=4, 119=5, 120=20, 121=4, 122=8, 123=5, 124=187, 126=9, 127=3, 128=560, 640=43, 5761=1, 129=5, 130=8, 131=5, 132=3, 134=6, 135=17, 136=4, 137=6, 138=9, 139=7, 140=8, 141=2, 142=6, 143=2, 144=9, 145=10, 146=6, 148=21, 661=4, 149=3, 150=12, 151=7, 1176=1, 152=3, 153=4, 154=2, 155=2, 156=6, 157=2, 159=2, 160=85, 162=2, 163=3, 164=9, 165=1, 166=3, 167=3, 170=2, 171=2, 174=18, 175=2, 178=4, 179=5, 180=18, 182=1, 183=2, 184=2, 186=1, 187=2, 188=2, 191=2, 192=33, 197=2, 198=3, 200=46, 201=2, 202=1, 204=4, 208=4, 210=4, 211=8, 1748=9, 213=1, 214=2, 220=4, 221=1, 734=1, 222=2, 225=2, 226=1, 227=3, 228=4, 236=2, 240=16, 245=1, 250=10, 252=32, 254=4, 256=300, 1792=1, 768=2, 260=118, 262=2, 780=1, 268=2, 781=1, 270=3, 272=4, 276=2, 1302=1, 280=2, 796=2, 1824=1, 800=8, 288=2, 300=1, 301=2, 304=2, 308=4, 1850=1, 316=2, 320=9, 324=2, 1351=2, 330=2, 331=3, 333=2, 340=2, 343=13, 858=2, 348=2, 350=9, 353=1, 361=1, 363=1, 372=1, 888=2, 384=12, 400=7, 412=2, 1437=1, 413=1, 430=2, 434=1, 440=2, 442=1, 443=1, 1467=2, 447=2, 456=2, 459=2, 976=2, 2000=1, 473=2, 1000=5, 500=19, 1534=2</code>
<img src="https://user-images.githubusercontent.com/68151306/146077847-febb21cf-df59-4063-9404-aa35691fb621.png">
<img src="https://user-images.githubusercontent.com/68151306/146078812-d22e161e-e910-4ffe-bc46-f870db41a3b9.png">
With resourcepack (Automatically compresses default textures to sizes smaller than 32x32 pixels with BufferedImage) <code>Number of pixels by width = the number of textures with a given number of pixels in width
</code><br>
<code>32=5325, 16=3487, 17=229, 18=298, 19=188, 20=362, 21=515, 22=210, 23=164, 24=351, 25=311, 26=458, 27=152, 28=122, 29=86, 30=98, 31=352</code>
<img src="https://user-images.githubusercontent.com/68151306/146077334-e059b386-d994-49b2-9713-9135862d534c.png">
<img src="https://user-images.githubusercontent.com/68151306/146079007-e2acba94-6fca-4454-8004-6d75e237ad56.png">
</details>

Hbm's Nuclear Tech Mod Reloaded can only be partially reduced RAM consumption with a resource pack that only replaces textures (without changing models).
<details>
  <summary>Hbm's Nuclear Tech Mod Reloaded</summary>
Without resourcepack <code>Number of pixels by width = the number of textures with a given number of pixels in width
</code><br>
<code>256=319, 512=37, 1024=15, 2304=1, 768=4, 2048=3, 1280=2, 1025=3, 794=1, 32=203, 800=1, 288=1, 34=3, 36=15, 38=5, 40=25, 42=2, 44=6, 300=4, 46=3, 48=35, 50=2, 51=1, 52=5, 56=5, 60=2, 62=1, 64=192, 66=3, 68=4, 70=1, 840=1, 72=10, 73=1, 74=3, 76=4, 78=1, 592=1, 80=2, 81=1, 82=4, 84=9, 85=1, 86=5, 598=1, 88=12, 90=1, 92=3, 94=3, 96=20, 352=1, 100=11, 103=3, 360=1, 106=3, 110=5, 112=31, 368=1, 117=1, 118=1, 121=1, 128=198, 640=3, 130=1, 132=4, 136=6, 144=3, 400=1, 150=5, 152=2, 156=1, 157=1, 160=34, 416=3, 163=1, 164=1, 166=4, 168=5, 172=4, 176=1, 184=2, 189=1, 448=3, 705=1, 193=1, 194=1, 200=1, 202=2, 205=4, 206=1, 208=5, 720=1, 721=1, 470=1, 991=1, 224=1, 228=1, 236=1, 240=5, 500=1, 248=1</code>
<img src="https://user-images.githubusercontent.com/68151306/146079362-5ede0f6e-d216-4f74-9502-22e77ad9f217.png">
With resourcepack (Automatically compresses default textures to sizes smaller than 32x32 pixels with BufferedImage) <code>tNumber of pixels by width = the number of textures with a given number of pixels in width
</code><br>
<code>32=768, 16=210, 17=14, 18=45, 19=14, 20=77, 21=26, 22=25, 23=13, 24=62, 25=27, 26=17, 27=5, 28=41, 29=4, 30=9, 31=3</code>
<img src="https://user-images.githubusercontent.com/68151306/146079896-02930bc0-4286-4767-a793-01422b52c0a7.png">
</details>
Lycanite's mobs can not be reduced RAM consumption by changing textures without changing models.
<br><br>
<strong>Alternative Solution:</strong><br>
Delete Pixelmon, Pokecube AIO and Hbm's Nuclear Tech Mod Reloaded.<br><br>
<strong>Additional context</strong><br>
Meme in a Bottle also has large textures and can be reduced RAM consumption with a resource pack that only replaces textures.

**Comment by WolfBV** [comment]
Pokecube, my beloved

**Comment by ThePansmith** [comment]
Pixelmon isn't in this pack yet, as I am building things from the ground up, but I appreciate the heads up.
